lab_1/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *

app_name='lab_1'
urlpatterns = [
    path('', views.index, name='index'),
    path('about_me/', views.about_me, name='about_me'),
    path('contact_me/', views.contact_me, name='contact_me'),
    path('contact_me/thank_you/', views.thank_you, name='thank_you'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/example/', views.portfolio_ex, name='portfolio_ex'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/add_schedule/', views.add_schedule, name='add_schedule'),
    path('schedule/delete/<schedule_name>)', views.delete_schedule, name='delete_schedule')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lab_1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab_1.urls')), #Ada di app lab_1
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_1/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    message = models.TextField()

    def __str__(self):
        return self.name

class Schedule(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(max_length=30)
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.name

lab_1/forms.py
from django import forms

class Add_Schedule(forms.Form):
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'name',
        'placeholder':'Timothy Wimbledon',
    }
    date_attrs = {
        'type': 'date',
        'class': 'form-control',
        'id':'date'
    }
    time_attrs = {
        'type': 'time',
        'class': 'form-control',
        'id':'time',
    }
    place_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'exampleInputEmail1',
        'placeholder':'NeverWinter',
    }
    category_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'exampleInputEmail1',
        'placeholder':'Outting',
    }

    name = forms.CharField(label='Name ', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    date = forms.DateTimeField(label='Date ', required=True, widget=forms.DateInput(attrs=date_attrs))
    time = forms.TimeField(label='Time ', required=True, widget=forms.TimeInput(attrs=time_attrs))
    place = forms.CharField(label='Place ', required=True, max_length=30, widget=forms.TextInput(attrs=place_attrs))
    category = forms.CharField(label='Category ', required=True, max_length=30, widget=forms.TextInput(attrs=category_attrs))

class Add_Contact(forms.Form):
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'name',
        'placeholder':'Timothy Wimbledon',
    }
    email_attrs = {
        'type': 'email',
        'class': 'form-control',
        'id':'email'
    }
    message_attrs = {
        'class': 'form-control',
        'id':'message',
        'rows':'3'
    }

    name = forms.CharField(label='Name ', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    email = forms.EmailField(label='Email ', required=True, widget=forms.TextInput(attrs=email_attrs))
    message = forms.CharField(label='Message ', required=True, max_length=200, widget=forms.TextInput(attrs=message_attrs))
    

lab_1/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import  reverse_lazy
from datetime import datetime, date
from .forms import Add_Schedule, Add_Contact    
from .models import Contact, Schedule

# Create your views here.

def index(request):
    response = {}
    return render(request, 'lab_1/index.html', response)

def about_me(request):
    response = {}
    return render(request, 'lab_1/about_me.html', response)

def contact_me(request):
    form = Add_Contact(request.POST or None)
    response = {'form_contact' : Add_Contact, 'success' : '',}
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['message'] = request.POST['message']
        response['success'] = "success"
        contact = Contact(name=response['name'], email=response['email'], message=response['message'])
        contact.save()
        return render(request, 'lab_1/contact_me.html', response)
    else:
        return render(request, 'lab_1/contact_me.html', response)

    
def portfolio(request):
    return render(request, 'lab_1/portfolio.html', {})

def thank_you(request):
    return render(request, 'lab_1/thank_you.html', {})

def portfolio_ex(request):
    return render(request, 'lab_1/portfolio_ex.html', {})

def schedule(request):
    schedule = Schedule.objects.all().values()
    response = {'list_schedule' : schedule}
    if(request.method == 'POST'):
        for i in request.POST :
            print(i)
    return render(request, 'lab_1/schedule.html', response)

def add_schedule(request):
    form = Add_Schedule(request.POST or None)
    response = {'form_schedule' : Add_Schedule}
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        schedule = Schedule(name=response['name'], date=response['date'], time=response['time'], place=response['place'], category=response['category'])
        schedule.save()
    return render(request, 'lab_1/add_schedule.html', response)

def delete_schedule(request, schedule_name):
    schedule_1 = Schedule.objects.get(name = schedule_name)
    response = {'schedule_name' : str(schedule_1.name)}
    schedule_1.delete()
    return render(request, 'lab_1/delete_schedule.html', response)

lab_1/templates/lab_1/about_me.html
{% extends 'lab_1/base.html' %}

{% block content %}
<div class="container pt-5 pb-5">
    <div class="card mx-auto transparet-bg-gray" style="width: 100%;">
        <div class="card-body">
            <p class="big-text pt-3 pb-3">
                My name is Randy Hidayah Putra Desnantara<br>
                <br>
                I am a CS college student at University of Indonesia<br>
                <br>
                My hobby is take a walk in nature and caving in the mancave<br>
                <br>
                Pizza is love Pizza is live<br>
            </p>
        </div>
    </div>
</div>
{% endblock %}

lab_1/templates/lab_1/add_schedule.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
    	
<div class="container pb-5 pt-5 mx-auto">
    <div class="big-text pb-1">Add Schedule</div>
    <form id="form_1" action="{% url 'lab_1:add_schedule' %}" method="POST">
        {% csrf_token %}    
        <div class="form-group">
            {{ form_schedule }} 
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>	
</div>
{% endblock %}

lab_1/templates/lab_1/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Homescreen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'lab_1/css/lab_1.css' %}"> 
    <link rel="stylesheet" href="{% static 'lab_1/css/bootstrap.css' %}"> 
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light transparet-bg-green">
        <div class="container">
            <a class="navbar-brand" href="{% url 'lab_1:index' %}">
                <img src="{% static 'lab_1/images/ProfilePicture.JPG' %}" class="rounded-circle" width="75" height="75" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:portfolio' %}">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:about_me' %}">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:schedule' %}">My Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:contact_me' %}">Contact Me</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
    {% block content %}
    {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="page-footer navbar-static-bottom font-small transparet-bg-green pt-4">

        <!-- Footer Links -->
        <div class="container text-center text-md-left">

            <!-- Grid row -->
            <div class="row d-flex align-items-center">

                <!-- Grid column -->
                <div class="col-md-7 col-lg-8">

                    <!--Copyright-->
                    <p class="text-center text-md-left">© 2019 Copyright: Randy Desnantara
                    </p>

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-5 col-lg-4 ml-lg-0">

                    <!-- Social buttons -->
                    <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://www.instagram.com/randydesnantara/">
                                <img src="{% static 'lab_1/images/Instagram.png' %}" width="25" height="25" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://twitter.com/Randyptr">
                                <img src="{% static 'lab_1/images/Twitter.png' %}" width="25" height="25" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://www.youtube.com/channel/UCrQRbEk69hs4z145S2WMcdQ?view_as=subscriber">
                                <img src="{% static 'lab_1/images/Youtube.png' %}" width="25" height="25"    alt="">
                            </a>
                        </li>
                    </ul>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->

    </footer>
<!-- Footer -->
</body>
</html>

lab_1/templates/lab_1/contact_me.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
<div class="container pb-5 pt-5 mx-auto">
    <div class="big-text pb-1">If you want to learn more, you can contact me trough here</div>
    <form id="form_1" action="{% url 'lab_1:contact_me' %}" method="POST">
        {% csrf_token %}    
        <div class="form-group">
            {{ form_contact }} 
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
  </form>	
</div>

{% endblock %}

lab_1/templates/lab_1/delete_schedule.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
    	
<div class="container pb-5 pt-5 mx-auto">
    <div class="big-text pb-1 pt-1">Schedule Succesfully Deleted</div><br><br>
    <div class="mid-text pb-1 pt-1">You have delete Schedule {{schedule_name}}</div><br><br><br>
    <a href="{% url 'lab_1:index' %}">Back to main menu</a>
</div>
{% endblock %}

lab_1/templates/lab_1/index.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url( "{% static 'lab_1/images/RinjaniSunriseRandy.jpeg' %}" );
        background-size: cover; 
        height: 100%;
    }
</style>

<div class="container pt-5 pb-5">
    <div class="card mx-auto transparet-bg-gray" style="width: 100%;">
        <div class="card-body">
            <p class="card-text big-text">Welcome to my site, dear user<br>
            <br>
            I am Randy<br>
            <br>
            Nothing but just a humble newbee front-end/back-end developer<br>
            Please continue to explore it<br>
            <br>
            <a class="btn btn-primary" href="{% url 'lab_1:about_me' %}">Go Now</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}

lab_1/templates/lab_1/portfolio.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="container">
        <div class="row pt-5">
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-5 pb-5">
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top transparet-bg-gray">
                    <div class="card-body">
                        <h5 class="card-title">Mirage AI</h5>
                        <p class="card-text">AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge...</p>
                        <a href="{% url 'lab_1:portfolio_ex' %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lab_1/templates/lab_1/portfolio_ex.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="container pt-5 pb-5">
        <div class="row transparet-bg-gray pt-5">
            <div class="col pl-5"> <img src="{% static 'lab_1/images/catto.png' %}" class="card-img-top"></div>
            <div class="col pl-3 pr-5">
                <p class="mid-text">
                    Description<br>
                    <br>
                    AI is an intelligence found in machine created using an alghoritm. AI will respond to many user input trough its knowledge. Mirage is an AI which can transform a still looking picture with a potrait of someone into a moving video. It recognize facial expression and distinguis it from background picture. It can create various expression and emotion into the video. 
                </p>
            </div>
        </div>
        <div class="row transparet-bg-gray pb-5 pl-5">20 April 2020 - 06 March 2021</div>
    </div>
</div>
{% endblock %}

lab_1/templates/lab_1/schedule.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}

<div class="container pb-5 pt-5 mx-auto">
    <div class="big-text pb-1">List of my current Schedule :</div><br>
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Schedule Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Place</th>
                        <th scope="col">Category</th>
                        <th scope="col">Delete Schedule</th>
                    </tr>
                </thead>
                <tbody> 
                    {% for schedule in list_schedule %}
                    <tr>
                        <th scope="row">{{ schedule.name }}</th>
                        <td>{{ schedule.date }}</td>
                        <td>{{ schedule.time }}</td>
                        <td>{{ schedule.place }}</td>
                        <td>{{ schedule.category }}</td>
                        <td>
                            <a  href="{% url 'lab_1:delete_schedule' schedule_name=schedule.name %}" method="POST">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </a>	
                        </td>   
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    <div class="big-text pb-1">Here a link to add schedule <a href="{% url 'lab_1:add_schedule' %}">Add Schedule</a></div>
</div>

{% endblock %}

lab_1/templates/lab_1/thank_you.html
{% extends 'lab_1/base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url( "{% static 'lab_1/images/RinjaniSunsetRandy.jpeg' %}" );
        background-size: cover; 
        height: 100%;
    }
</style>

<div class="container container-fullscreen">
    <div class="container pt-5 pb-5">
        <div class="card mx-auto transparet-bg-gray" style="width: 100%;">
            <div class="card-body">
                <p class="big-text">
                    Thank You, you can go back to home <a href="{% url 'lab_1:index' %}" class="blue-text">here</a>
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}